### ISSUE TITLE
parse-names on embedded backslash commands

### ISSUE THREAD

**Issue by mn200** [mattmight/bib2sx#5]
The following input

```
@inproceedings{foo,
  author    = {Rastislav Bod{\'{\i}}k},
  title     = {Some Test}
}
```

and command `bib2sx --parse-names` fails with a parse error.  If you remove the outer braces to turn the last name into `Bod\'{\i}k`, then the parser splits the name into 

```
  (author (name (first "Rastislav" " " "Bod\\'") (von) (last '"\\i" "k") (jr)))
```

which is wrong.  

If you change it to `Bod{\'\i}k`, you get

```
  (author (name (first "Rastislav" " " "Bod") (von) (last '"\\'\\i" "k") (jr)))
```

The form with two sets of braces comes from a DBLP record; I don't know if it, or any of the others, is correct BibTeX.

**Comment by mattmight** [comment]
Thanks! I know what's causing this. 

Using the "von Last, First" format should work until I can fix.

—

**Comment by mattmight** [comment]
I've revamped the name-parsing system entirely so that it first re-lexes the names into words.

This fixes that specific error and (I suspect) others.  Thanks!
